import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./auth-context";
import Header from "./Header";
import Sidebar from "./Sidebar";
import DashboardLayout from "./DashboardLayout";

export const metadata: Metadata = {
  title: "movies recommendation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 antialiased min-h-screen">
        <AuthProvider>
          <DashboardLayout>{children}</DashboardLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
